[project]
name = "EasyMocap"
version = "0.1.0"
description = "Add a short description here"
authors = ["pablovela5620 <pablovela5620@gmail.com>"]
channels = ["nvidia/label/cuda-11.8.0", "nvidia", "conda-forge", "pytorch"]
platforms = ["linux-64"]

[tasks]
torch-gpu-check = """
    python -c "import torch; print(torch.__version__);print(torch.cuda.is_available())"
"""
_install-chumpy = { cmd = "pip install git+https://github.com/gobanana520/chumpy.git", description = "Installs chumpy" }
post-install = { cmd = "python -m pip install -e .", depends-on = [
    "_install-chumpy",
] }

[dependencies]
python = "==3.11"
pip = ">=25.0.1,<26"
rerun-sdk = ">=0.12.0,<0.13"
pytorch = { version = ">=2.2.0,<2.3", channel = "pytorch" }
torchvision = { version = ">=0.17.0,<0.18", channel = "pytorch" }
icecream = ">=2.1.3,<2.2"
jaxtyping = ">=0.2.25,<0.3"
tqdm = ">=4.66.2,<4.67"
pyrender = ">=0.1.45,<0.2"
tabulate = ">=0.9.0,<0.10"
termcolor = ">=2.4.0,<2.5"
pandas = ">=2.2.0,<2.3"

[pypi-dependencies]
mediapipe = "==0.10.8"

[target.linux-64.dependencies]
cuda = { version = "*", channel = "nvidia/label/cuda-11.8.0" }
pytorch-cuda = { version = "11.8.*", channel = "pytorch" }
